- name: Persist metrics (commit JSONL)
  if: always() && github.event_name == 'pull_request' && github.actor != 'dependabot[bot]'
  run: |
    git config user.name  "github-actions[bot]"
    git config user.email "github-actions[bot]@users.noreply.github.com"
    mkdir -p artefacts/reports
    git add artefacts/reports/ci-metrics.jsonl artefacts/loop_logs || true
    git commit -m "chore(ci): persist metrics & loop-log [skip ci]" || echo "nothing to commit"
    git push origin HEAD:${{ github.head_ref }}
