name: auto-format

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          persist-credentials: true
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - name: Prettier write
        run: npx --yes prettier --write .
      - name: Commit & push formatted files
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -am "chore(prettier): auto-format via CI" || echo "nothing to commit"
          git push origin HEAD:${{ github.head_ref }}
