name: docs-lite
on:
  pull_request:
    paths:
      - "**/*.md"
      - ".markdownlint.yml"
      - ".gitattributes"
jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-node@v4
        with: { node-version: "20" }
      - run: npm i -g markdownlint-cli prettier
      - name: Normalize & fix markdown
        run: |
          node tools/fix-md.mjs || true
          prettier --write "**/*.md" || true
          markdownlint "**/*.md" -c .markdownlint.yml --fix || true
      - name: Commit markdown fixes (if any)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "docs: auto-fix markdown (docs-lite)"
            git push
          else
            echo "No markdown fixes to commit"
          fi
