name: governance-min

on:
  pull_request:
    branches: [main]
    paths:
      - '**'
      - '!**/.github/workflows/**'

permissions:
  contents: read

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with: { node-version: 20 }

      - name: Init summary
        run: |
          {
            echo "# Baseline Governance (read-only)";
            echo "";
            echo "- No commits by CI";
            echo "- All checks are soft (warnings only)";
          } >> "$GITHUB_STEP_SUMMARY"

      - name: Prettier (check only, soft)
        run: |
          npx --yes prettier --check . \
            || { echo "::warning::Prettier check failed (soft)"; true; }

      - name: UTF-8 / BOM / spacing (soft, only if script exists)
        if: ${{ hashFiles('scripts/check-utf8.mjs') != '' }}
        run: |
          node scripts/check-utf8.mjs --root . \
            || { echo "::warning::UTF-8 check failed (soft)"; true; }

      - name: Ticket validation (non-strict, soft, only if script exists)
        if: ${{ hashFiles('scripts/validate-ticket.mjs') != '' }}
        run: |
          node scripts/validate-ticket.mjs \
            || { echo "::warning::Ticket validation reported issues (soft)"; true; }

      - name: Summary
        run: |
          {
            echo "";
            echo "## Results";
            echo "- Prettier: soft-checked";
            echo "- UTF-8: soft-checked (if script present)";
            echo "- Tickets: soft-checked (if script present)";
          } >> "$GITHUB_STEP_SUMMARY"

      - name: Always succeed
        run: echo "✅ governance-min completed"
