name: governance

on:
  pull_request:
    branches: [ main ]

jobs:
  run-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Prettier
        run: npx --yes prettier --check .
      - name: Markdownlint
        run: |
          if [ -f .markdownlint.yml ]; then
            npx --yes markdownlint "**/*.md" -c .markdownlint.yml -d
          else
            echo "No .markdownlint.yml, skipping."
          fi

  run-utf8:
    runs-on: ubuntu-latest
    needs: run-checks
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: UTF-8 / BOM / spacing
        run: node scripts/check-utf8.mjs --root .

  collect-changed:
    runs-on: ubuntu-latest
    needs: run-utf8
    outputs:
      tickets: ${{ steps.set.outputs.tickets }}
    steps:
      - uses: actions/checkout@v4
      - name: Collect changed tickets
        id: set
        shell: bash
        run: |
          BASE=${{ github.base_ref }}
          CHANGED=$(git diff --name-only origin/$BASE...${{ github.sha }} | grep -E '^tickets/AT-[0-9]+\.md$' || true)
          echo "tickets=$(printf '%s\n' "$CHANGED" | jq -R -s 'split("\n")|map(select(length>0))')" >> "$GITHUB_OUTPUT"

  validate-all:
    runs-on: ubuntu-latest
    needs: collect-changed
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Validate all tickets (non-strict)
        run: node scripts/validate-ticket.mjs

  validate-changed:
    runs-on: ubuntu-latest
    needs: collect-changed
    if: ${{ fromJson(needs.collect-changed.outputs.tickets).length > 0 }}
    strategy:
      matrix:
        file: ${{ fromJson(needs.collect-changed.outputs.tickets) }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Validate changed ticket (strict)
        run: node scripts/validate-ticket.mjs --strict --file "${{ matrix.file }}"
