name: governance

on:
  pull_request:
    branches: [main]

jobs:
  validate-tickets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      # Liste ge채nderter Ticket-Dateien (gegen base branch)
      - name: Get changed tickets
        id: diff
        run: |
          CHANGED=$(git diff --name-only origin/${{ github.base_ref }}...${{ github.sha }} | grep -E '^tickets/AT-[0-9]+\.md$' || true)
          echo "changed=$CHANGED" >> $GITHUB_OUTPUT

      # Non-strict f체r alle Tickets (Bestandsvalidierung)
      - name: Validate all tickets (non-strict)
        run: node scripts/validate-ticket.mjs

      # Strict nur f체r ge채nderte Tickets
      - name: Validate changed tickets (strict)
        if: ${{ steps.diff.outputs.changed != '' }}
        run: |
          for f in ${{ steps.diff.outputs.changed }}; do
            node scripts/validate-ticket.mjs --strict --file "$f"
          done
          
  run-checks:
    runs-on: ubuntu-latest
    needs: setup-node
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Prettier
        run: npx --yes prettier --check .
      - name: Markdownlint
        run: |
          if [ -x node_modules/.bin/markdownlint ]; then
            npx markdownlint "**/*.md" -c .markdownlint.yml
          elif command -v markdownlint >/dev/null 2>&1; then
            markdownlint "**/*.md" -c .markdownlint.yml
          else
            echo "markdownlint not installed, skipping."
          fi

  run-utf8:
    runs-on: ubuntu-latest
    needs: setup-node
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: node scripts/check-utf8.mjs --root .

  validate-tickets:
    runs-on: ubuntu-latest
    needs: setup-node
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: node scripts/validate-ticket.mjs --strict
